site_name: Lecture Note
theme:
        name: material
        features:
                - navigation.tabs

site_url: https://lecturenote.pipats.xyz/
repo_url: https://github.com/saengowp/LectureNote
# markdown_extensions:
